import type { WallpaperState } from '@/types/wallpaper'
import {
  createDefaultBackgroundProfileSlots,
  createDefaultLogoProfileSlots,
  createDefaultSpectrumProfileSlots,
} from '@/lib/featureProfiles'
import { IMAGE_BASS_ZOOM_CLASSIC } from '@/features/presets/imageBassZoomProfiles'

export const DEFAULT_STATE: WallpaperState = {
  // Background FX
  noiseIntensity: 0.0,
  rgbShift: 0.003,
  scanlineIntensity: 0.12,
  scanlineMode: 'always',
  scanlineSpacing: 800,
  scanlineThickness: 1.2,
  parallaxStrength: 0.03,
  backgroundImageEnabled: true,
  imageUrl: null,
  imageScale: 1.0,
  imagePositionX: 0.0,
  imagePositionY: 0.0,
  imageOpacity: 1,
  imageBassReactive: false,
  imageBassScaleIntensity: 0.5,
  imageAudioReactiveDecay: 0.62,
  ...IMAGE_BASS_ZOOM_CLASSIC,
  imageBassZoomPresetId: 'classic',
  imageAudioChannel: 'kick',
  backgroundProfileSlots: createDefaultBackgroundProfileSlots(),
  imageFitMode: 'cover',
  imageMirror: false,
  showBackgroundScaleMeter: false,
  showSpectrumDiagnosticsHud: false,
  showLogoDiagnosticsHud: false,
  filterTarget: 'background',
  filterBrightness: 1,
  filterContrast: 1,
  filterSaturation: 1,
  filterBlur: 0,
  filterHueRotate: 0,
  globalBackgroundEnabled: true,
  globalBackgroundId: null,
  globalBackgroundUrl: null,
  globalBackgroundScale: 1,
  globalBackgroundPositionX: 0,
  globalBackgroundPositionY: 0,
  globalBackgroundFitMode: 'cover',
  globalBackgroundOpacity: 1,
  globalBackgroundBrightness: 1,
  globalBackgroundContrast: 1,
  globalBackgroundSaturation: 1,
  globalBackgroundBlur: 0,
  globalBackgroundHueRotate: 0,

  rgbShiftAudioReactive: false,
  rgbShiftAudioSensitivity: 0.008,
  rgbShiftAudioChannel: 'hihat',

  // Audio
  audioReactive: false,
  audioSensitivity: 1.0,
  audioCaptureState: 'idle',
  audioPaused: false,
  motionPaused: false,
  fftSize: 2048,
  audioSmoothing: 0.8,
  audioChannelSmoothing: 0.42,
  audioSelectedChannelSmoothing: 0.18,
  audioAutoKickThreshold: 0.08,
  audioAutoSwitchHoldMs: 180,
  audioTrackTitleEnabled: false,
  audioTrackTitleLayoutMode: 'centered',
  audioTrackTitleFontStyle: 'techno',
  audioTrackTitleUppercase: false,
  audioTrackTitlePositionX: 0,
  audioTrackTitlePositionY: -0.76,
  audioTrackTitleFontSize: 28,
  audioTrackTitleLetterSpacing: 0,
  audioTrackTitleWidth: 0.42,
  audioTrackTitleOpacity: 0.95,
  audioTrackTitleScrollSpeed: 42,
  audioTrackTitleRgbShift: 0,
  audioTrackTitleTextColor: '#f8fafc',
  audioTrackTitleGlowColor: '#00eaff',
  audioTrackTitleGlowBlur: 18,
  audioTrackTitleBackdropEnabled: true,
  audioTrackTitleBackdropColor: '#020617',
  audioTrackTitleBackdropOpacity: 0.5,
  audioTrackTitleBackdropPadding: 12,
  audioTrackTitleFilterBrightness: 1,
  audioTrackTitleFilterContrast: 1,
  audioTrackTitleFilterSaturation: 1,
  audioTrackTitleFilterBlur: 0,
  audioTrackTitleFilterHueRotate: 0,

  // Spectrum
  spectrumEnabled: true,
  spectrumMode: 'radial',
  spectrumLinearOrientation: 'horizontal',
  spectrumLinearDirection: 'normal',
  spectrumRadialShape: 'circle',
  spectrumRadialAngle: 0,
  spectrumRadialFitLogo: true,
  spectrumFollowLogo: false,
  spectrumLogoGap: 8,
  spectrumCircularClone: false,
  spectrumSpan: 1,
  spectrumCloneOpacity: 0.72,
  spectrumCloneScale: 0.9,
  spectrumCloneGap: 8,
  spectrumCloneStyle: 'bars',
  spectrumCloneRadialShape: 'circle',
  spectrumCloneRadialAngle: 0,
  spectrumCloneBarCount: 96,
  spectrumCloneBarWidth: 2,
  spectrumInnerRadius: 80,
  spectrumBarCount: 128,
  spectrumBarWidth: 2,
  spectrumMinHeight: 2,
  spectrumMaxHeight: 120,
  spectrumSmoothing: 0.75,
  spectrumOpacity: 0.9,
  spectrumGlowIntensity: 0.8,
  spectrumShadowBlur: 18,
  spectrumPrimaryColor: '#00ffff',
  spectrumSecondaryColor: '#ff00ff',
  spectrumColorMode: 'gradient',
  spectrumBandMode: 'auto',
  spectrumShape: 'bars',
  spectrumRotationSpeed: 0,
  spectrumMirror: true,
  spectrumPeakHold: true,
  spectrumPeakDecay: 0.003,
  spectrumPositionX: 0,
  spectrumPositionY: 0,
  spectrumProfileSlots: createDefaultSpectrumProfileSlots(),

  // Logo
  logoEnabled: false,
  logoUrl: null,
  logoBaseSize: 80,
  logoPositionX: 0,
  logoPositionY: 0,
  logoBandMode: 'kick',
  logoAudioSensitivity: 3.8,
  logoReactiveScaleIntensity: 0.9,
  logoReactivitySpeed: 0.68,
  logoAttack: 0.95,
  logoRelease: 0.05,
  logoMinScale: 1,
  logoMaxScale: 1.85,
  logoPunch: 0.4,
  logoPeakWindow: 1.9,
  logoPeakFloor: 0.1,
  logoGlowColor: '#00ffff',
  logoGlowBlur: 30,
  logoShadowEnabled: true,
  logoShadowColor: '#00ffff',
  logoShadowBlur: 40,
  logoBackdropEnabled: true,
  logoBackdropColor: '#000000',
  logoBackdropOpacity: 0.5,
  logoBackdropPadding: 20,
  logoProfileSlots: createDefaultLogoProfileSlots(),

  // Particles
  particlesEnabled: true,
  particleLayerMode: 'both',
  particleShape: 'circles',
  particleColor1: '#00ffff',
  particleColor2: '#ff00ff',
  particleColorMode: 'gradient',
  particleSizeMin: 4,
  particleSizeMax: 14,
  particleOpacity: 0.7,
  particleGlow: true,
  particleGlowStrength: 0.6,
  particleFilterBrightness: 1,
  particleFilterContrast: 1,
  particleFilterSaturation: 1,
  particleFilterBlur: 0,
  particleFilterHueRotate: 0,
  particleScanlineIntensity: 0,
  particleScanlineSpacing: 760,
  particleScanlineThickness: 1.2,
  particleRotationIntensity: 0,
  particleRotationDirection: 'clockwise',
  particleFadeInOut: true,
  particleAudioReactive: true,
  particleAudioChannel: 'instrumental',
  particleAudioSizeBoost: 2.0,
  particleAudioOpacityBoost: 0.3,
  particleCount: 60,
  particleSpeed: 0.5,

  // Rain
  rainEnabled: false,
  rainIntensity: 0.5,
  rainDropCount: 50,
  rainAngle: 10,
  rainMeshRotationZ: 0,
  rainColor: '#a0c8ff',
  rainColorMode: 'solid',
  rainParticleType: 'lines',
  rainLength: 0.12,
  rainWidth: 0.0015,
  rainBlur: 0.002,
  rainSpeed: 0.8,
  rainVariation: 0.35,

  // Slideshow
  slideshowEnabled: false,
  slideshowInterval: 30,
  slideshowTransitionDuration: 1.0,
  slideshowTransitionType: 'fade' as const,
  slideshowTransitionIntensity: 1,
  slideshowTransitionAudioDrive: 0,
  slideshowTransitionAudioChannel: 'instrumental',
  slideshowResetPosition: false,
  activeImageId: null,
  backgroundImages: [],
  imageUrls: [],

  // Persistence
  imageIds: [],
  logoId: null,
  overlays: [],
  selectedOverlayId: null,

  // System
  performanceMode: 'medium',
  customPresets: {},
  activePreset: 'custom:session',
  language: 'en',
  isPresetDirty: false,
  showFps: true,
  controlPanelAnchor: 'bottom-right',
  fpsOverlayAnchor: 'top-left',
  editorTheme: 'glass',
  layerZIndices: {},
}

export const PARTICLE_LIMITS: Record<string, number> = {
  low: 20,
  medium: 80,
  high: 200,
}
