import type { WallpaperState } from '@/types/wallpaper'

export const DEFAULT_STATE: WallpaperState = {
  // Background FX
  glitchIntensity: 0.0,
  glitchFrequency: 0.85,
  glitchStyle: 'bands',
  noiseIntensity: 0.0,
  rgbShift: 0.003,
  scanlineIntensity: 0.12,
  scanlineMode: 'always',
  scanlineSpacing: 800,
  scanlineThickness: 1.2,
  parallaxStrength: 0.03,
  imageUrl: null,
  imageScale: 1.0,
  imagePositionX: 0.0,
  imagePositionY: 0.0,
  imageBassReactive: false,
  imageBassScaleIntensity: 0.5,
  imageFitMode: 'cover',
  filterTarget: 'background',
  filterBrightness: 1,
  filterContrast: 1,
  filterSaturation: 1,
  filterBlur: 0,
  filterHueRotate: 0,

  // Glitch audio
  glitchAudioReactive: false,
  glitchAudioSensitivity: 0.4,
  rgbShiftAudioReactive: false,
  rgbShiftAudioSensitivity: 0.008,

  // Audio
  audioReactive: false,
  audioSensitivity: 1.0,
  audioCaptureState: 'idle',
  fftSize: 2048,
  audioSmoothing: 0.8,

  // Spectrum
  spectrumEnabled: true,
  spectrumFollowLogo: false,
  spectrumRadius: 180,
  spectrumInnerRadius: 80,
  spectrumBarCount: 128,
  spectrumBarWidth: 2,
  spectrumMinHeight: 2,
  spectrumMaxHeight: 120,
  spectrumSmoothing: 0.75,
  spectrumOpacity: 0.9,
  spectrumGlowIntensity: 0.8,
  spectrumShadowBlur: 18,
  spectrumPrimaryColor: '#00ffff',
  spectrumSecondaryColor: '#ff00ff',
  spectrumColorMode: 'gradient',
  spectrumBandMode: 'full',
  spectrumShape: 'bars',
  spectrumLayout: 'circular',
  spectrumDirection: 'clockwise',
  spectrumRotationSpeed: 0,
  spectrumMirror: true,
  spectrumPeakHold: true,
  spectrumPeakDecay: 0.003,
  spectrumPositionX: 0,
  spectrumPositionY: 0,

  // Logo
  logoEnabled: false,
  logoUrl: null,
  logoBaseSize: 80,
  logoAudioSensitivity: 3.0,
  logoReactiveScaleIntensity: 0.7,
  logoReactivitySpeed: 0.5,
  logoAttack: 0.8,
  logoRelease: 0.08,
  logoMinScale: 1,
  logoMaxScale: 1.85,
  logoPunch: 0.3,
  logoGlowColor: '#00ffff',
  logoGlowBlur: 30,
  logoShadowEnabled: true,
  logoShadowColor: '#00ffff',
  logoShadowBlur: 40,
  logoBackdropEnabled: true,
  logoBackdropColor: '#000000',
  logoBackdropOpacity: 0.5,
  logoBackdropPadding: 20,

  // Particles
  particlesEnabled: true,
  particleLayerMode: 'both',
  particleShape: 'circles',
  particleColor1: '#00ffff',
  particleColor2: '#ff00ff',
  particleColorMode: 'gradient',
  particleSizeMin: 4,
  particleSizeMax: 14,
  particleOpacity: 0.7,
  particleGlow: true,
  particleGlowStrength: 0.6,
  particleFadeInOut: true,
  particleAudioReactive: true,
  particleAudioSizeBoost: 2.0,
  particleAudioOpacityBoost: 0.3,
  particleCount: 60,
  particleSpeed: 0.5,

  // Rain
  rainEnabled: false,
  rainIntensity: 0.5,
  rainDropCount: 50,
  rainAngle: 10,
  rainMeshRotationZ: 0,
  rainColor: '#a0c8ff',
  rainColorMode: 'solid',
  rainParticleType: 'lines',
  rainLength: 0.12,
  rainWidth: 0.0015,
  rainBlur: 0.002,
  rainSpeed: 0.8,
  rainVariation: 0.35,

  // Slideshow
  slideshowEnabled: false,
  slideshowInterval: 30,
  slideshowTransitionDuration: 1.0,
  slideshowTransitionType: 'fade' as const,
  slideshowResetPosition: false,
  imageUrls: [],

  // Persistence
  imageIds: [],
  logoId: null,
  overlays: [],
  selectedOverlayId: null,

  // System
  performanceMode: 'medium',
  customPresets: {},
  activePreset: 'custom:session',
  language: 'en',
  isPresetDirty: false,
  layerZIndices: {},
}

export const PARTICLE_LIMITS: Record<string, number> = {
  low: 20,
  medium: 80,
  high: 200,
}
