import type {
  ControllerLayer,
  OverlayLayer,
  SceneLayer,
  WallpaperLayer,
} from '@/types/layers'
import type { WallpaperState } from '@/types/wallpaper'

function sortLayers<T extends WallpaperLayer>(layers: T[]): T[] {
  return [...layers].sort((a, b) => a.zIndex - b.zIndex)
}

function resolveZIndex(
  state: WallpaperState,
  id: keyof WallpaperState['layerZIndices'],
  fallback: number
): number {
  return state.layerZIndices[id] ?? fallback
}

export function buildSceneLayers(state: WallpaperState): SceneLayer[] {
  return sortLayers([
    {
      id: 'background-image',
      type: 'background-image',
      kind: 'scene',
      enabled: true,
      zIndex: resolveZIndex(state, 'background-image', 0),
      opacity: 1,
      positionX: state.imagePositionX,
      positionY: state.imagePositionY,
      scale: state.imageScale,
      rotation: 0,
      blendMode: 'normal',
      locked: true,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.imageBassReactive,
        sensitivity: state.imageBassScaleIntensity,
        bandSource: 'bass',
      },
      imageUrl: state.imageUrl,
      fitMode: state.imageFitMode,
      mirror: state.imageMirror,
      transitionType: state.slideshowTransitionType,
      transitionDuration: state.slideshowTransitionDuration,
      transitionIntensity: state.slideshowTransitionIntensity,
      transitionAudioDrive: state.slideshowTransitionAudioDrive,
    },
    {
      id: 'particle-background',
      type: 'particle-background',
      kind: 'scene',
      enabled: state.particlesEnabled && (state.particleLayerMode === 'background' || state.particleLayerMode === 'both'),
      zIndex: resolveZIndex(state, 'particle-background', 10),
      opacity: state.particleOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'additive',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.particleAudioReactive,
        sensitivity: state.particleAudioSizeBoost,
        bandSource: 'full',
      },
      count: state.particleCount,
      shape: state.particleShape,
      layerMode: state.particleLayerMode,
    },
    {
      id: 'rain',
      type: 'rain',
      kind: 'scene',
      enabled: state.rainEnabled && state.performanceMode !== 'low',
      zIndex: resolveZIndex(state, 'rain', 20),
      opacity: state.rainIntensity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: state.rainMeshRotationZ,
      blendMode: 'screen',
      locked: false,
      draggable: false,
      particleType: state.rainParticleType,
      colorMode: state.rainColorMode,
    },
    {
      id: 'particle-foreground',
      type: 'particle-foreground',
      kind: 'scene',
      enabled: state.particlesEnabled && (state.particleLayerMode === 'foreground' || state.particleLayerMode === 'both'),
      zIndex: resolveZIndex(state, 'particle-foreground', 30),
      opacity: state.particleOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'additive',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.particleAudioReactive,
        sensitivity: state.particleAudioOpacityBoost,
        bandSource: 'full',
      },
      count: state.particleCount,
      shape: state.particleShape,
      layerMode: state.particleLayerMode,
    },
  ])
}

export function buildOverlayLayers(state: WallpaperState): OverlayLayer[] {
  return sortLayers([
    ...state.overlays.map((overlay) => ({
      id: overlay.id,
      type: 'overlay-image' as const,
      kind: 'overlay' as const,
      enabled: overlay.enabled,
      zIndex: overlay.zIndex,
      opacity: overlay.opacity,
      positionX: overlay.positionX,
      positionY: overlay.positionY,
      scale: overlay.scale,
      rotation: overlay.rotation,
      blendMode: overlay.blendMode,
      locked: false,
      draggable: true,
      assetId: overlay.assetId,
      imageUrl: overlay.url,
      name: overlay.name,
      cropShape: overlay.cropShape,
      edgeFade: overlay.edgeFade,
      edgeBlur: overlay.edgeBlur,
      edgeGlow: overlay.edgeGlow,
      width: overlay.width,
      height: overlay.height,
    })),
    {
      id: 'logo',
      type: 'logo',
      kind: 'overlay',
      enabled: state.logoEnabled,
      zIndex: resolveZIndex(state, 'logo', 60),
      opacity: 1,
      positionX: state.logoPositionX,
      positionY: state.logoPositionY,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: true,
        sensitivity: state.logoAudioSensitivity,
        bandSource: state.logoBandMode,
      },
      imageUrl: state.logoUrl,
      baseSize: state.logoBaseSize,
    },
    {
      id: 'track-title',
      type: 'track-title',
      kind: 'overlay',
      enabled: state.audioTrackTitleEnabled,
      zIndex: resolveZIndex(state, 'track-title', 65),
      opacity: state.audioTrackTitleOpacity,
      positionX: state.audioTrackTitlePositionX,
      positionY: state.audioTrackTitlePositionY,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: false,
      maxWidthRatio: state.audioTrackTitleWidth,
      fontSize: state.audioTrackTitleFontSize,
      scrollSpeed: state.audioTrackTitleScrollSpeed,
    },
    {
      id: 'spectrum',
      type: 'spectrum',
      kind: 'overlay',
      enabled: state.spectrumEnabled,
      zIndex: resolveZIndex(state, 'spectrum', 70),
      opacity: state.spectrumOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'screen',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: true,
        sensitivity: state.audioSensitivity,
        bandSource: state.spectrumBandMode === 'full' ? 'full' : state.spectrumBandMode,
      },
      layout: state.spectrumLayout,
      shape: state.spectrumShape,
      followLogo: state.spectrumFollowLogo,
    },
  ])
}

export function buildControllerLayers(state: WallpaperState): ControllerLayer[] {
  return sortLayers([
    {
      id: 'slideshow',
      type: 'slideshow',
      kind: 'controller',
      enabled: state.slideshowEnabled && state.backgroundImages.length > 1,
      zIndex: resolveZIndex(state, 'slideshow', 5),
      opacity: 1,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: false,
      interval: state.slideshowInterval,
      transitionDuration: state.slideshowTransitionDuration,
      imageCount: state.backgroundImages.length,
    },
  ])
}
