import type {
  ControllerLayer,
  OverlayLayer,
  SceneLayer,
  WallpaperLayer,
} from '@/types/layers'
import type { WallpaperState } from '@/types/wallpaper'

function sortLayers<T extends WallpaperLayer>(layers: T[]): T[] {
  return [...layers].sort((a, b) => a.zIndex - b.zIndex)
}

export function buildSceneLayers(state: WallpaperState): SceneLayer[] {
  return sortLayers([
    {
      id: 'background-image',
      type: 'background-image',
      kind: 'scene',
      enabled: true,
      zIndex: 0,
      opacity: 1,
      positionX: state.imagePositionX,
      positionY: state.imagePositionY,
      scale: state.imageScale,
      rotation: 0,
      blendMode: 'normal',
      locked: true,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.imageBassReactive,
        sensitivity: state.imageBassScaleIntensity,
        bandSource: 'bass',
      },
      imageUrl: state.imageUrl,
      fitMode: state.imageFitMode,
    },
    {
      id: 'particle-background',
      type: 'particle-background',
      kind: 'scene',
      enabled: state.particlesEnabled && (state.particleLayerMode === 'background' || state.particleLayerMode === 'both'),
      zIndex: 10,
      opacity: state.particleOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'additive',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.particleAudioReactive,
        sensitivity: state.particleAudioSizeBoost,
        bandSource: 'full',
      },
      count: state.particleCount,
      shape: state.particleShape,
      layerMode: state.particleLayerMode,
    },
    {
      id: 'rain',
      type: 'rain',
      kind: 'scene',
      enabled: state.rainEnabled && state.performanceMode !== 'low',
      zIndex: 20,
      opacity: state.rainIntensity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: state.rainMeshRotationZ,
      blendMode: 'screen',
      locked: false,
      draggable: false,
      particleType: state.rainParticleType,
      colorMode: state.rainColorMode,
    },
    {
      id: 'particle-foreground',
      type: 'particle-foreground',
      kind: 'scene',
      enabled: state.particlesEnabled && (state.particleLayerMode === 'foreground' || state.particleLayerMode === 'both'),
      zIndex: 30,
      opacity: state.particleOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'additive',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: state.particleAudioReactive,
        sensitivity: state.particleAudioOpacityBoost,
        bandSource: 'full',
      },
      count: state.particleCount,
      shape: state.particleShape,
      layerMode: state.particleLayerMode,
    },
    {
      id: 'fx',
      type: 'fx',
      kind: 'scene',
      enabled: state.glitchIntensity > 0 || state.rgbShift > 0 || state.scanlineIntensity > 0 || state.noiseIntensity > 0,
      zIndex: 40,
      opacity: 1,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'screen',
      locked: true,
      draggable: false,
      glitchEnabled: state.glitchIntensity > 0 || state.rgbShift > 0,
      scanlinesEnabled: state.scanlineIntensity > 0,
    },
  ])
}

export function buildOverlayLayers(state: WallpaperState): OverlayLayer[] {
  return sortLayers([
    {
      id: 'fixed-overlay-image',
      type: 'fixed-overlay-image',
      kind: 'overlay',
      enabled: false,
      zIndex: 50,
      opacity: 1,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: true,
      imageUrl: null,
    },
    {
      id: 'logo',
      type: 'logo',
      kind: 'overlay',
      enabled: state.logoEnabled,
      zIndex: 60,
      opacity: 1,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: true,
        sensitivity: state.logoAudioSensitivity,
        bandSource: 'bass',
      },
      imageUrl: state.logoUrl,
      baseSize: state.logoBaseSize,
    },
    {
      id: 'spectrum',
      type: 'spectrum',
      kind: 'overlay',
      enabled: state.spectrumEnabled,
      zIndex: 70,
      opacity: state.spectrumOpacity,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'screen',
      locked: false,
      draggable: false,
      audioReactiveConfig: {
        enabled: true,
        sensitivity: state.audioSensitivity,
        bandSource: state.spectrumBandMode === 'full' ? 'full' : state.spectrumBandMode,
      },
      layout: state.spectrumLayout,
      shape: state.spectrumShape,
      followLogo: state.spectrumFollowLogo,
    },
  ])
}

export function buildControllerLayers(state: WallpaperState): ControllerLayer[] {
  return sortLayers([
    {
      id: 'slideshow',
      type: 'slideshow',
      kind: 'controller',
      enabled: state.slideshowEnabled && state.imageUrls.length > 1,
      zIndex: 5,
      opacity: 1,
      positionX: 0,
      positionY: 0,
      scale: 1,
      rotation: 0,
      blendMode: 'normal',
      locked: false,
      draggable: false,
      interval: state.slideshowInterval,
      transitionDuration: state.slideshowTransitionDuration,
      imageCount: state.imageUrls.length,
    },
  ])
}
