import type { SpectrumProfileSettings } from '@/types/wallpaper';

export type SpectrumPresetTier = 'light' | 'medium' | 'heavy';

export type SpectrumPreset = {
	id: string;
	name: string;
	description: string;
	category: 'radial' | 'linear' | 'cinematic';
	tags: string[];
	/** Primary color used for thumbnail swatch */
	swatchA: string;
	/** Secondary color used for thumbnail gradient */
	swatchB: string;
	performanceTier: SpectrumPresetTier;
	settings: SpectrumProfileSettings;
};

// ─── Shared clone defaults (disable clone for most presets) ─────────────────

const NO_CLONE: Pick<
	SpectrumProfileSettings,
	| 'spectrumFamily'
	| 'spectrumOscilloscopeLineWidth'
	| 'spectrumTunnelRingCount'
	| 'spectrumSpectrogramDecay'
	| 'spectrumCircularClone'
	| 'spectrumCloneOpacity'
	| 'spectrumCloneScale'
	| 'spectrumCloneGap'
	| 'spectrumCloneStyle'
	| 'spectrumCloneRadialShape'
	| 'spectrumCloneRadialAngle'
	| 'spectrumCloneBarCount'
	| 'spectrumCloneBarWidth'
	| 'spectrumCloneMinHeight'
	| 'spectrumCloneMaxHeight'
	| 'spectrumCloneSmoothing'
	| 'spectrumCloneGlowIntensity'
	| 'spectrumCloneShadowBlur'
	| 'spectrumClonePrimaryColor'
	| 'spectrumCloneSecondaryColor'
	| 'spectrumCloneColorSource'
	| 'spectrumCloneColorMode'
	| 'spectrumCloneBandMode'
	| 'spectrumCloneAudioSmoothingEnabled'
	| 'spectrumCloneAudioSmoothing'
	| 'spectrumCloneRotationSpeed'
	| 'spectrumCloneMirror'
	| 'spectrumClonePeakHold'
	| 'spectrumClonePeakDecay'
	| 'spectrumCloneWaveFillOpacity'
> = {
	spectrumFamily: 'classic',
	spectrumOscilloscopeLineWidth: 2,
	spectrumTunnelRingCount: 12,
	spectrumSpectrogramDecay: 0.95,
	spectrumCircularClone: false,
	spectrumCloneOpacity: 0.72,
	spectrumCloneScale: 0.9,
	spectrumCloneGap: 8,
	spectrumCloneStyle: 'bars',
	spectrumCloneRadialShape: 'circle',
	spectrumCloneRadialAngle: 0,
	spectrumCloneBarCount: 96,
	spectrumCloneBarWidth: 2,
	spectrumCloneMinHeight: 2,
	spectrumCloneMaxHeight: 96,
	spectrumCloneSmoothing: 0.78,
	spectrumCloneGlowIntensity: 0.7,
	spectrumCloneShadowBlur: 16,
	spectrumClonePrimaryColor: '#00ffff',
	spectrumCloneSecondaryColor: '#ff00ff',
	spectrumCloneColorSource: 'manual',
	spectrumCloneColorMode: 'gradient',
	spectrumCloneBandMode: 'auto',
	spectrumCloneAudioSmoothingEnabled: true,
	spectrumCloneAudioSmoothing: 0.18,
	spectrumCloneRotationSpeed: 0,
	spectrumCloneMirror: true,
	spectrumClonePeakHold: true,
	spectrumClonePeakDecay: 0.003,
	spectrumCloneWaveFillOpacity: 0.28
};

// ─── Presets ─────────────────────────────────────────────────────────────────

export const SPECTRUM_PRESETS: SpectrumPreset[] = [
	{
		id: 'neon-halo',
		name: 'Neon Halo',
		description: 'Anillo de onda que abraza el logo con brillo neón intenso.',
		category: 'radial',
		tags: ['neon', 'wave', 'glow', 'logo'],
		swatchA: '#ff006e',
		swatchB: '#00d4ff',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'radial',
			spectrumShape: 'wave',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: true,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 12,
			spectrumInnerRadius: 90,
			spectrumBarCount: 128,
			spectrumBarWidth: 2.5,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 160,
			spectrumSmoothing: 0.8,
			spectrumOpacity: 0.92,
			spectrumGlowIntensity: 1.6,
			spectrumShadowBlur: 24,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#ff006e',
			spectrumSecondaryColor: '#00d4ff',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.18,
			spectrumRotationSpeed: 0.1,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'glass-scope',
		name: 'Glass Scope',
		description: 'Barras cristalinas lineares, minimalistas y limpias.',
		category: 'linear',
		tags: ['minimal', 'clean', 'bars', 'blue'],
		swatchA: '#4fc3f7',
		swatchB: '#e0f7fa',
		performanceTier: 'light',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'linear',
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumShape: 'bars',
			spectrumPositionY: -0.82,
			spectrumPositionX: 0,
			spectrumSpan: 0.9,
			spectrumBarCount: 64,
			spectrumBarWidth: 3,
			spectrumMinHeight: 1,
			spectrumMaxHeight: 140,
			spectrumSmoothing: 0.7,
			spectrumOpacity: 0.72,
			spectrumGlowIntensity: 0.2,
			spectrumShadowBlur: 0,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#4fc3f7',
			spectrumSecondaryColor: '#e0f7fa',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0,
			spectrumMirror: false,
			spectrumPeakHold: true,
			spectrumPeakDecay: 0.004,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0
		}
	},

	{
		id: 'aurora-ribbon',
		name: 'Aurora Ribbon',
		description: 'Cinta de onda arcoíris que flota en el fondo como una aurora.',
		category: 'cinematic',
		tags: ['rainbow', 'wave', 'aurora', 'cinematic'],
		swatchA: '#69ff47',
		swatchB: '#cc40ff',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'linear',
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumShape: 'wave',
			spectrumPositionY: 0,
			spectrumPositionX: 0,
			spectrumSpan: 1.0,
			spectrumBarCount: 96,
			spectrumBarWidth: 3,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 180,
			spectrumSmoothing: 0.82,
			spectrumOpacity: 0.88,
			spectrumGlowIntensity: 0.9,
			spectrumShadowBlur: 14,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'rainbow',
			spectrumPrimaryColor: '#69ff47',
			spectrumSecondaryColor: '#cc40ff',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.32,
			spectrumRotationSpeed: 0,
			spectrumMirror: true,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0
		}
	},

	{
		id: 'monster-tunnel',
		name: 'Monster Tunnel',
		description: 'Bloques de fuego radiales con radio interno alto. Agresivo.',
		category: 'radial',
		tags: ['blocks', 'fire', 'aggressive', 'bass'],
		swatchA: '#ff4500',
		swatchB: '#ff8c00',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'radial',
			spectrumShape: 'blocks',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: false,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 180,
			spectrumBarCount: 64,
			spectrumBarWidth: 4,
			spectrumMinHeight: 3,
			spectrumMaxHeight: 140,
			spectrumSmoothing: 0.65,
			spectrumOpacity: 0.95,
			spectrumGlowIntensity: 2.0,
			spectrumShadowBlur: 30,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#ff4500',
			spectrumSecondaryColor: '#ff8c00',
			spectrumBandMode: 'bass',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.12,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0.4,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'crt-pulse',
		name: 'CRT Pulse',
		description: 'Cápsulas verdes con peak hold. Estética terminal retro.',
		category: 'linear',
		tags: ['retro', 'crt', 'green', 'capsules', 'peak'],
		swatchA: '#00ff41',
		swatchB: '#004d00',
		performanceTier: 'light',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'linear',
			spectrumLinearOrientation: 'vertical',
			spectrumLinearDirection: 'normal',
			spectrumShape: 'capsules',
			spectrumPositionX: 0,
			spectrumPositionY: 0,
			spectrumSpan: 0.85,
			spectrumBarCount: 80,
			spectrumBarWidth: 4,
			spectrumMinHeight: 1,
			spectrumMaxHeight: 220,
			spectrumSmoothing: 0.72,
			spectrumOpacity: 0.9,
			spectrumGlowIntensity: 1.0,
			spectrumShadowBlur: 10,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'solid',
			spectrumPrimaryColor: '#00ff41',
			spectrumSecondaryColor: '#00ff41',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0,
			spectrumMirror: true,
			spectrumPeakHold: true,
			spectrumPeakDecay: 0.002,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0
		}
	},

	{
		id: 'liquid-core',
		name: 'Liquid Core',
		description: 'Onda radial azul-violeta con relleno fluido. Hipnótico.',
		category: 'radial',
		tags: ['liquid', 'wave', 'blue', 'violet', 'chill'],
		swatchA: '#0080ff',
		swatchB: '#8000ff',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'radial',
			spectrumShape: 'wave',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumBarCount: 128,
			spectrumBarWidth: 2,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 150,
			spectrumSmoothing: 0.85,
			spectrumOpacity: 0.88,
			spectrumGlowIntensity: 1.2,
			spectrumShadowBlur: 20,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#0080ff',
			spectrumSecondaryColor: '#8000ff',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.2,
			spectrumWaveFillOpacity: 0.38,
			spectrumRotationSpeed: 0.15,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'arc-reactor',
		name: 'Arc Reactor',
		description: 'Barras en hexágono con alto brillo. Futurista y potente.',
		category: 'radial',
		tags: ['hexagon', 'bars', 'sci-fi', 'cyan', 'glow'],
		swatchA: '#00e5ff',
		swatchB: '#2962ff',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'radial',
			spectrumShape: 'bars',
			spectrumRadialShape: 'hexagon',
			spectrumRadialAngle: 30,
			spectrumFollowLogo: true,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 10,
			spectrumInnerRadius: 100,
			spectrumBarCount: 96,
			spectrumBarWidth: 2,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 130,
			spectrumSmoothing: 0.74,
			spectrumOpacity: 0.95,
			spectrumGlowIntensity: 1.8,
			spectrumShadowBlur: 22,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#00e5ff',
			spectrumSecondaryColor: '#2962ff',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0.05,
			spectrumMirror: false,
			spectrumPeakHold: true,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'signal-bloom',
		name: 'Signal Bloom',
		description: 'Puntos arcoíris que explotan con cada frecuencia. Festivo.',
		category: 'linear',
		tags: ['dots', 'rainbow', 'festive', 'bloom', 'glow'],
		swatchA: '#ffffff',
		swatchB: '#ffff00',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'linear',
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumShape: 'dots',
			spectrumPositionY: -0.78,
			spectrumPositionX: 0,
			spectrumSpan: 1.0,
			spectrumBarCount: 128,
			spectrumBarWidth: 4,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 220,
			spectrumSmoothing: 0.7,
			spectrumOpacity: 0.95,
			spectrumGlowIntensity: 1.5,
			spectrumShadowBlur: 18,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'rainbow',
			spectrumPrimaryColor: '#ffffff',
			spectrumSecondaryColor: '#ffff00',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.15,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0
		}
	},

	{
		id: 'laser-chamber',
		name: 'Laser Chamber',
		description: 'Picos rojo-naranja disparados verticalmente. Alta energía.',
		category: 'linear',
		tags: ['spikes', 'red', 'energy', 'vertical', 'aggressive'],
		swatchA: '#ff1744',
		swatchB: '#ff6d00',
		performanceTier: 'light',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'linear',
			spectrumLinearOrientation: 'vertical',
			spectrumLinearDirection: 'flipped',
			spectrumShape: 'spikes',
			spectrumPositionX: 0.82,
			spectrumPositionY: 0,
			spectrumSpan: 0.9,
			spectrumBarCount: 64,
			spectrumBarWidth: 5,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 260,
			spectrumSmoothing: 0.65,
			spectrumOpacity: 0.92,
			spectrumGlowIntensity: 2.0,
			spectrumShadowBlur: 28,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#ff1744',
			spectrumSecondaryColor: '#ff6d00',
			spectrumBandMode: 'bass',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.12,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0
		}
	},

	{
		id: 'dream-static',
		name: 'Dream Static',
		description: 'Puntos rosados en rotación suave. Onírico y relajante.',
		category: 'radial',
		tags: ['dots', 'pink', 'dreamy', 'chill', 'slow'],
		swatchA: '#ff80ab',
		swatchB: '#b39ddb',
		performanceTier: 'light',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumMode: 'radial',
			spectrumShape: 'dots',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 60,
			spectrumBarCount: 180,
			spectrumBarWidth: 3,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 110,
			spectrumSmoothing: 0.88,
			spectrumOpacity: 0.85,
			spectrumGlowIntensity: 0.8,
			spectrumShadowBlur: 12,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#ff80ab',
			spectrumSecondaryColor: '#b39ddb',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.22,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0.3,
			spectrumMirror: true,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	}
];

// ── New family presets ──────────────────────────────────────────────────────

export const SPECTRUM_FAMILY_PRESETS: SpectrumPreset[] = [
	{
		id: 'scope-pulse',
		name: 'Scope Pulse',
		description: 'Forma de onda circular que late con el audio. Scope clásico.',
		category: 'radial',
		tags: ['oscilloscope', 'waveform', 'pulse', 'radial'],
		swatchA: '#00ff88',
		swatchB: '#00aaff',
		performanceTier: 'light',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumFamily: 'oscilloscope',
			spectrumOscilloscopeLineWidth: 2.5,
			spectrumTunnelRingCount: 12,
			spectrumSpectrogramDecay: 0.95,
			spectrumMode: 'radial',
			spectrumShape: 'bars',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 100,
			spectrumBarCount: 128,
			spectrumBarWidth: 2.5,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 160,
			spectrumSmoothing: 0.8,
			spectrumOpacity: 0.92,
			spectrumGlowIntensity: 1.4,
			spectrumShadowBlur: 20,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#00ff88',
			spectrumSecondaryColor: '#00aaff',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.14,
			spectrumRotationSpeed: 0.06,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'spectrogram-storm',
		name: 'Spectrogram Storm',
		description: 'Cascada de frecuencias en tiempo real. Visualización científica.',
		category: 'cinematic',
		tags: ['spectrogram', 'waterfall', 'rainbow', 'data'],
		swatchA: '#ff0080',
		swatchB: '#ffff00',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumFamily: 'spectrogram',
			spectrumOscilloscopeLineWidth: 2,
			spectrumTunnelRingCount: 12,
			spectrumSpectrogramDecay: 0.92,
			spectrumMode: 'linear',
			spectrumShape: 'bars',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumBarCount: 128,
			spectrumBarWidth: 2,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 120,
			spectrumSmoothing: 0.75,
			spectrumOpacity: 0.95,
			spectrumGlowIntensity: 0,
			spectrumShadowBlur: 0,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'rainbow',
			spectrumPrimaryColor: '#ff0080',
			spectrumSecondaryColor: '#ffff00',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: false,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0,
			spectrumRotationSpeed: 0,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'hypno-tunnel',
		name: 'Hypno Tunnel',
		description: 'Anillos concéntricos pulsantes. Efecto hipnótico de profundidad.',
		category: 'radial',
		tags: ['tunnel', 'rings', 'hypnotic', 'bass', 'depth'],
		swatchA: '#aa00ff',
		swatchB: '#ff6600',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumFamily: 'tunnel',
			spectrumOscilloscopeLineWidth: 2,
			spectrumTunnelRingCount: 16,
			spectrumSpectrogramDecay: 0.95,
			spectrumMode: 'radial',
			spectrumShape: 'bars',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: false,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 40,
			spectrumBarCount: 64,
			spectrumBarWidth: 2,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 180,
			spectrumSmoothing: 0.7,
			spectrumOpacity: 0.9,
			spectrumGlowIntensity: 1.6,
			spectrumShadowBlur: 20,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#aa00ff',
			spectrumSecondaryColor: '#ff6600',
			spectrumBandMode: 'bass',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0.28,
			spectrumRotationSpeed: 0.3,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'liquid-dream',
		name: 'Liquid Dream',
		description: 'Ondas fluidas superpuestas en azul-verde. Meditativo y suave.',
		category: 'cinematic',
		tags: ['liquid', 'wave', 'fluid', 'chill', 'layered'],
		swatchA: '#00c9ff',
		swatchB: '#00ff88',
		performanceTier: 'medium',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumFamily: 'liquid',
			spectrumOscilloscopeLineWidth: 2,
			spectrumTunnelRingCount: 12,
			spectrumSpectrogramDecay: 0.95,
			spectrumMode: 'linear',
			spectrumShape: 'wave',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 80,
			spectrumBarCount: 96,
			spectrumBarWidth: 2.5,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 140,
			spectrumSmoothing: 0.84,
			spectrumOpacity: 0.88,
			spectrumGlowIntensity: 1.0,
			spectrumShadowBlur: 16,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#00c9ff',
			spectrumSecondaryColor: '#00ff88',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.22,
			spectrumWaveFillOpacity: 0.22,
			spectrumRotationSpeed: 0,
			spectrumMirror: true,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	},

	{
		id: 'orbital-nova',
		name: 'Orbital Nova',
		description: 'Partículas orbitando en cáscaras de energía. Cósmico e hipnótico.',
		category: 'radial',
		tags: ['orbital', 'particles', 'cosmic', 'trails', 'glow'],
		swatchA: '#ff9900',
		swatchB: '#ff00aa',
		performanceTier: 'heavy',
		settings: {
			...NO_CLONE,
			spectrumEnabled: true,
			spectrumFamily: 'orbital',
			spectrumOscilloscopeLineWidth: 2,
			spectrumTunnelRingCount: 12,
			spectrumSpectrogramDecay: 0.95,
			spectrumMode: 'radial',
			spectrumShape: 'dots',
			spectrumRadialShape: 'circle',
			spectrumRadialAngle: 0,
			spectrumFollowLogo: false,
			spectrumRadialFitLogo: true,
			spectrumLogoGap: 8,
			spectrumInnerRadius: 60,
			spectrumBarCount: 96,
			spectrumBarWidth: 3,
			spectrumMinHeight: 2,
			spectrumMaxHeight: 200,
			spectrumSmoothing: 0.78,
			spectrumOpacity: 0.88,
			spectrumGlowIntensity: 1.6,
			spectrumShadowBlur: 24,
			spectrumColorSource: 'manual',
			spectrumColorMode: 'gradient',
			spectrumPrimaryColor: '#ff9900',
			spectrumSecondaryColor: '#ff00aa',
			spectrumBandMode: 'auto',
			spectrumAudioSmoothingEnabled: true,
			spectrumAudioSmoothing: 0.18,
			spectrumWaveFillOpacity: 0,
			spectrumRotationSpeed: 0.4,
			spectrumMirror: false,
			spectrumPeakHold: false,
			spectrumPeakDecay: 0.003,
			spectrumLinearOrientation: 'horizontal',
			spectrumLinearDirection: 'normal',
			spectrumSpan: 1,
			spectrumPositionX: 0,
			spectrumPositionY: 0
		}
	}
];

// Merge all presets into a single list accessible to the gallery
export const ALL_SPECTRUM_PRESETS = [...SPECTRUM_PRESETS, ...SPECTRUM_FAMILY_PRESETS];

export function findPresetById(id: string): SpectrumPreset | undefined {
	return ALL_SPECTRUM_PRESETS.find(p => p.id === id);
}
