import { useShallow } from 'zustand/react/shallow';
import { useWallpaperStore } from '@/store/wallpaperStore';

export function useQuickActionsState() {
	return useWallpaperStore(
		useShallow(state => ({
			quickActionsEnabled: state.quickActionsEnabled,
			quickActionsPositionX: state.quickActionsPositionX,
			quickActionsPositionY: state.quickActionsPositionY,
			quickActionsLauncherPositionX: state.quickActionsLauncherPositionX,
			quickActionsLauncherPositionY: state.quickActionsLauncherPositionY,
			quickActionsBackdropOpacity: state.quickActionsBackdropOpacity,
			quickActionsBlurPx: state.quickActionsBlurPx,
			quickActionsScale: state.quickActionsScale,
			quickActionsLauncherSize: state.quickActionsLauncherSize,
			layoutResponsiveEnabled: state.layoutResponsiveEnabled,
			layoutReferenceWidth: state.layoutReferenceWidth,
			layoutReferenceHeight: state.layoutReferenceHeight,
			quickActionsColorSource: state.quickActionsColorSource,
			syncAllColorSources: state.syncAllColorSources,
			quickActionsManualAccentColor: state.quickActionsManualAccentColor,
			quickActionsManualSecondaryColor:
				state.quickActionsManualSecondaryColor,
			quickActionsManualBackdropColor:
				state.quickActionsManualBackdropColor,
			quickActionsManualTextPrimaryColor:
				state.quickActionsManualTextPrimaryColor,
			quickActionsManualTextSecondaryColor:
				state.quickActionsManualTextSecondaryColor,
			quickActionsManualSurfaceOpacity:
				state.quickActionsManualSurfaceOpacity,
			quickActionsManualItemOpacity: state.quickActionsManualItemOpacity,
			editorTheme: state.editorTheme,
			editorCornerRadius: state.editorCornerRadius,
			editorControlCornerRadius: state.editorControlCornerRadius,
			logoUrl: state.logoUrl,
			backgroundImages: state.backgroundImages,
			activeImageId: state.activeImageId,
			setActiveImageId: state.setActiveImageId,
			audioTracks: state.audioTracks,
			activeAudioTrackId: state.activeAudioTrackId,
			spectrumProfileSlots: state.spectrumProfileSlots,
			loadSpectrumProfileSlot: state.loadSpectrumProfileSlot,
			looksProfileSlots: state.looksProfileSlots,
			loadLooksProfileSlot: state.loadLooksProfileSlot,
			motionProfileSlots: state.motionProfileSlots,
			loadMotionProfileSlot: state.loadMotionProfileSlot,
			particlesProfileSlots: state.particlesProfileSlots,
			loadParticlesProfileSlot: state.loadParticlesProfileSlot,
			rainProfileSlots: state.rainProfileSlots,
			loadRainProfileSlot: state.loadRainProfileSlot,
			logoProfileSlots: state.logoProfileSlots,
			loadLogoProfileSlot: state.loadLogoProfileSlot,
			trackTitleProfileSlots: state.trackTitleProfileSlots,
			loadTrackTitleProfileSlot: state.loadTrackTitleProfileSlot,
			backgroundImageEnabled: state.backgroundImageEnabled,
			setBackgroundImageEnabled: state.setBackgroundImageEnabled,
			globalBackgroundEnabled: state.globalBackgroundEnabled,
			setGlobalBackgroundEnabled: state.setGlobalBackgroundEnabled,
			slideshowEnabled: state.slideshowEnabled,
			setSlideshowEnabled: state.setSlideshowEnabled,
			spectrumEnabled: state.spectrumEnabled,
			setSpectrumEnabled: state.setSpectrumEnabled,
			logoEnabled: state.logoEnabled,
			setLogoEnabled: state.setLogoEnabled,
			audioTrackTitleEnabled: state.audioTrackTitleEnabled,
			setAudioTrackTitleEnabled: state.setAudioTrackTitleEnabled,
			audioTrackTimeEnabled: state.audioTrackTimeEnabled,
			setAudioTrackTimeEnabled: state.setAudioTrackTimeEnabled,
			particlesEnabled: state.particlesEnabled,
			setParticlesEnabled: state.setParticlesEnabled,
			particleLayerMode: state.particleLayerMode,
			setParticleLayerMode: state.setParticleLayerMode,
			rainEnabled: state.rainEnabled,
			setRainEnabled: state.setRainEnabled,
			overlays: state.overlays,
			updateOverlay: state.updateOverlay,
			motionPaused: state.motionPaused,
			setMotionPaused: state.setMotionPaused,
			imageBassReactive: state.imageBassReactive,
			setImageBassReactive: state.setImageBassReactive,
			imageMirror: state.imageMirror,
			setImageMirror: state.setImageMirror,
			imageOpacityReactive: state.imageOpacityReactive,
			setImageOpacityReactive: state.setImageOpacityReactive,
			imageAudioSmoothingEnabled: state.imageAudioSmoothingEnabled,
			setImageAudioSmoothingEnabled: state.setImageAudioSmoothingEnabled,
			particleAudioReactive: state.particleAudioReactive,
			setParticleAudioReactive: state.setParticleAudioReactive,
			particleGlow: state.particleGlow,
			setParticleGlow: state.setParticleGlow,
			particleFadeInOut: state.particleFadeInOut,
			setParticleFadeInOut: state.setParticleFadeInOut,
			spectrumAudioSmoothingEnabled: state.spectrumAudioSmoothingEnabled,
			setSpectrumAudioSmoothingEnabled:
				state.setSpectrumAudioSmoothingEnabled,
			spectrumMirror: state.spectrumMirror,
			setSpectrumMirror: state.setSpectrumMirror,
			spectrumPeakHold: state.spectrumPeakHold,
			setSpectrumPeakHold: state.setSpectrumPeakHold,
			spectrumCircularClone: state.spectrumCircularClone,
			setSpectrumCircularClone: state.setSpectrumCircularClone,
			logoAudioSmoothingEnabled: state.logoAudioSmoothingEnabled,
			setLogoAudioSmoothingEnabled: state.setLogoAudioSmoothingEnabled,
			logoShadowEnabled: state.logoShadowEnabled,
			setLogoShadowEnabled: state.setLogoShadowEnabled,
			logoBackdropEnabled: state.logoBackdropEnabled,
			setLogoBackdropEnabled: state.setLogoBackdropEnabled,
			audioTrackTitleBackdropEnabled:
				state.audioTrackTitleBackdropEnabled,
			setAudioTrackTitleBackdropEnabled:
				state.setAudioTrackTitleBackdropEnabled,
			rgbShiftAudioReactive: state.rgbShiftAudioReactive,
			setRgbShiftAudioReactive: state.setRgbShiftAudioReactive,
			rgbShiftAudioSmoothingEnabled:
				state.rgbShiftAudioSmoothingEnabled,
			setRgbShiftAudioSmoothingEnabled:
				state.setRgbShiftAudioSmoothingEnabled,
			audioCrossfadeEnabled: state.audioCrossfadeEnabled,
			setAudioCrossfadeEnabled: state.setAudioCrossfadeEnabled,
			audioAutoAdvance: state.audioAutoAdvance,
			setAudioAutoAdvance: state.setAudioAutoAdvance,
			audioFileLoop: state.audioFileLoop,
			setAudioFileLoop: state.setAudioFileLoop,
			audioReactive: state.audioReactive,
			setAudioReactive: state.setAudioReactive,
			mediaSessionEnabled: state.mediaSessionEnabled,
			setMediaSessionEnabled: state.setMediaSessionEnabled,
			audioTrackTitleUppercase: state.audioTrackTitleUppercase,
			setAudioTrackTitleUppercase: state.setAudioTrackTitleUppercase,
			slideshowAudioCheckpointsEnabled:
				state.slideshowAudioCheckpointsEnabled,
			setSlideshowAudioCheckpointsEnabled:
				state.setSlideshowAudioCheckpointsEnabled,
			slideshowTrackChangeSyncEnabled:
				state.slideshowTrackChangeSyncEnabled,
			setSlideshowTrackChangeSyncEnabled:
				state.setSlideshowTrackChangeSyncEnabled,
			slideshowManualTimestampsEnabled:
				state.slideshowManualTimestampsEnabled,
			setSlideshowManualTimestampsEnabled:
				state.setSlideshowManualTimestampsEnabled,
			slideshowResetPosition: state.slideshowResetPosition,
			setSlideshowResetPosition: state.setSlideshowResetPosition,
			spectrumFollowLogo: state.spectrumFollowLogo,
			setSpectrumFollowLogo: state.setSpectrumFollowLogo,
			spectrumRadialFitLogo: state.spectrumRadialFitLogo,
			setSpectrumRadialFitLogo: state.setSpectrumRadialFitLogo,
			spectrumCloneMirror: state.spectrumCloneMirror,
			setSpectrumCloneMirror: state.setSpectrumCloneMirror,
			spectrumClonePeakHold: state.spectrumClonePeakHold,
			setSpectrumClonePeakHold: state.setSpectrumClonePeakHold,
			spectrumCloneAudioSmoothingEnabled:
				state.spectrumCloneAudioSmoothingEnabled,
			setSpectrumCloneAudioSmoothingEnabled:
				state.setSpectrumCloneAudioSmoothingEnabled,
			spectrumCloneFollowLogo: state.spectrumCloneFollowLogo,
			setSpectrumCloneFollowLogo: state.setSpectrumCloneFollowLogo,
			spectrumCloneRadialFitLogo: state.spectrumCloneRadialFitLogo,
			setSpectrumCloneRadialFitLogo: state.setSpectrumCloneRadialFitLogo,
			showFps: state.showFps,
			setShowFps: state.setShowFps,
			sleepModeEnabled: state.sleepModeEnabled,
			setSleepModeEnabled: state.setSleepModeEnabled,
			layoutBackgroundReframeEnabled:
				state.layoutBackgroundReframeEnabled,
			setLayoutResponsiveEnabled: state.setLayoutResponsiveEnabled,
			setLayoutBackgroundReframeEnabled:
				state.setLayoutBackgroundReframeEnabled,
			setQuickActionsColorSource: state.setQuickActionsColorSource,
			setQuickActionsManualAccentColor:
				state.setQuickActionsManualAccentColor,
			setQuickActionsManualSecondaryColor:
				state.setQuickActionsManualSecondaryColor,
			setQuickActionsManualBackdropColor:
				state.setQuickActionsManualBackdropColor,
			setQuickActionsManualTextPrimaryColor:
				state.setQuickActionsManualTextPrimaryColor,
			setQuickActionsManualTextSecondaryColor:
				state.setQuickActionsManualTextSecondaryColor,
			setQuickActionsManualSurfaceOpacity:
				state.setQuickActionsManualSurfaceOpacity,
			setQuickActionsManualItemOpacity:
				state.setQuickActionsManualItemOpacity,
			performanceSafeEnabled: state.performanceSafeEnabled,
			setPerformanceSafeEnabled: state.setPerformanceSafeEnabled,
			virtualFoldersEnabled: state.virtualFoldersEnabled,
			setVirtualFoldersEnabled: state.setVirtualFoldersEnabled,
			showBackgroundScaleMeter: state.showBackgroundScaleMeter,
			setShowBackgroundScaleMeter: state.setShowBackgroundScaleMeter,
			showSpectrumDiagnosticsHud: state.showSpectrumDiagnosticsHud,
			setShowSpectrumDiagnosticsHud: state.setShowSpectrumDiagnosticsHud,
			showLogoDiagnosticsHud: state.showLogoDiagnosticsHud,
			setShowLogoDiagnosticsHud: state.setShowLogoDiagnosticsHud,
			setEditorTheme: state.setEditorTheme
		}))
	);
}

export type QuickActionsState = ReturnType<typeof useQuickActionsState>;
